# NumPy Library (Numerical Python)

In [ ]:
import numpy as np # common alias for numpy

print('Numpy Version: ', np.__version__)

Numpy Version:  2.5.3


### Properties of NumPy
-   Gives us access to the NumPy `Array` object.
-   Array manipulation
-   Array aggregation.
-   Data analysis, machine learning tasks
-   Processing Numerical data effeciently
-   Data Cleaning/Wrangling
-   When using Arrays they should be a single data type (homogeneous data)
-   `ndarray` - data type for a NumPy Array

#### Installing NumPy
-   `pip install numpy`

In [ ]:
# single dimensional arrays (Vector)

# Array type are determined automatically by numpy
# Declare a numpy array with list, tuple, range (sequence)

oneD = np.array(
    [1, 2, 3, 4, 5, 6]
)

print(oneD)
print(oneD[1:4:2])

[1 2 3 4 5 6]
[2 4]


In [ ]:
# Two dimensional array (Matrix) Grid. Similar to a table
twoD = np.array(
    [
        [1, 2, 3],
        [3, 4, 6],
        [7, 8, 9]
    ]
)

print(twoD)

[[1 2 3]
 [3 4 6]
 [7 8 9]]


In [14]:
# Three dimensional Array (Tensor). set of matrices
threeD = np.array(
    [
        [
            [1, 2],
            [3, 4]
        ],
        [
            [5, 6],
            [7, 8]
        ]
    ]
)

print(threeD)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
# N-dimensional - ndarray
# zero - based indexing
print(type(oneD))

print(type(oneD[3]))

<class 'numpy.ndarray'>
<class 'numpy.int64'>


### Declaring Arrays in Python
-   `.array()` - delarcing simple arrays with lists, tuples, ranges
-   `.arange()` - rangle function to create an array.
    -   syntax: `np.arange(start, stop, step, dtype)`

In [39]:
one_to_100 = np.arange(100)

print(one_to_100)

# array from 1 - 30 not including 30
one_thirty = np.arange(1, 30)
print(one_thirty)

# array from 10-20 by 2
ten_twenty = np.arange(10, 20, 2)
print(ten_twenty)

# array from -3 -10 10 by 4, verify dtype is int
print(np.arange(-3, 10, 4, dtype=int))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
[10 12 14 16 18]
[-3  1  5  9]


#### NumPy Array Attributes - Array descriptors
-   `array.shape` - tuple with the num of rows and columns
-   `array.size` - total number of elements (records) in array
-   `array.dtype` - data type of arrays
-   `array.ndim` - number of dimensions
-   can be used with pandas DF

In [44]:
print(oneD)
print(oneD.shape)
print(oneD.size)
print(oneD.dtype)
print(oneD.ndim)

[1 2 3 4 5 6]
(6,)
6
int64
1


### Random Numbers in NumPy

In [46]:
from numpy import random

In [60]:
# Generate random num between 0-1
print(random.rand())

# Generate random numbers with normal distribution
print(random.randn())

0.010375418478840936
1.6035969796948002


### NumPy Operations

In [72]:
# Array Access
arr = np.array([1, 2, 3, 4, 5])

element = arr[3]
print('Element: ', element)

slice = arr[1:4]
print('Slice: ', slice)

print(arr)

Element:  4
Slice:  [2 3 4]
[1 2 3 4 5]


In [73]:
# Arithmetic and NumPy Arrays
# Arithmetic with arrays and scalar values compute element-wise (PER ELEMENT, for each element)
arr = np.array([1, 2, 3])
arr2 = np.array([9, 8, 7])

print(arr + 1) #[2, 3, 4]
print(arr * 3) #[3, 6, 9]
print(arr / 2) # [0.5, 1.0, 1.5]

print(arr + arr2) # [10, 10, 10] added elements at the same index together.

[2 3 4]
[3 6 9]
[0.5 1.  1.5]
[10 10 10]


In [77]:
# NumPy Aggregations
arr = np.array([1, 2, 3, 4, 5])

sum = np.sum(arr)
mean = np.mean(arr)
median = np.median(arr)
stDev = np.std(arr)
min = np.min(arr)
max = np.max(arr)

print('Sum: ', sum)
print('Avg: ', mean)
print('Median: ', median)
print('Standard Deviation: ', stDev)
print('Min: ', min)
print('Max: ', max)

Sum:  15
Avg:  3.0
Median:  3.0
Standard Deviation:  1.4142135623730951
Min:  1
Max:  5


In [91]:
# Transpose or Reshape
matrix = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

print('Before Transpose')
print(matrix)
# Tranpose, pivot table 90 degrees
transpose_matrix = matrix.T
print('\nTransposed Matrix')
print(transpose_matrix)


reshaped_matrix = matrix.reshape(3, 2)

print('\nReshaped Matrix')
print(reshaped_matrix)

Before Transpose
[[1 2 3]
 [4 5 6]]

Transposed Matrix
[[1 4]
 [2 5]
 [3 6]]

Reshaped Matrix
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Logical Operators AND, OR NOT
a = np.array([True, True, False, False])
b = np.array([True, False, True, False])
print('Logical And') # compare each element in a list
print(np.logical_and(a, b))

print('\nLogical Or') # compare each element in a list
print(np.logical_or(a, b))

Logical And
[ True False False False]

Logical Or
[ True  True  True False]


In [101]:
c = np.array([True, True, False, False])
print(np.logical_not(c)) # Flips the boolean value

[False False  True  True]


In [103]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
c = np.array([2, 3, 4, 5])

print(np.array_equal(a, b)) # compares the entire array looking for differences.

print(np.array_equal(a, c))

True
False


In [110]:
# Sorting Arrays
a = np.array([3, 13, 6, 23, 14, 100, -1, -8, 32])

print(np.sort(a))

[ -8  -1   3   6  13  14  23  32 100]


In [116]:
# Searching

# Membership operators
print(12 not in a)
print(3 in a)

True
True


In [ ]:
b = np.array([3, 13, 6, 23, 14, 100, -1, -8, 32])
print(np.argmin(b)) # return the index number of the lower/minimum value

print(np.argmax(b)) # return the index number of the max value

7
5


In [123]:
# count_nonzero() - counts non-zero elements
a = np.array([0, 1, 2, 0, 13, 15, 0, 6])

print(np.count_nonzero(a))

b = np.array([
    [1, 2, 0],
    [0, 0, 0]
])

print(np.count_nonzero(b))

5
2


In [ ]:
# concatenate() - combines multiple arrays into one array

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.concatenate((a, b), axis=0)

print(c)

[1 2 3 4 5 6 7 8]
